=== cassiuste/MO373-DTDs/contact/contact.dtd
<!-- El root es el contacts-->
<!ELEMENT contacts (contact+)>
<!-- He indicado que el contacto puede tener un numero de mobil y puede o no tener un numero de linea-->
<!ELEMENT contact (name, lastName, mobileNum, landlineNum?, age, address+, email)>
<!-- contact tiene un atributo en el que indica si el contacto es un familiar o no-->
<!ATTLIST contact familyMember (yes|no) #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT mobileNum (#PCDATA)>
<!ELEMENT landlineNum (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT address (street, postalCode, city)>
<!-- La direccion tiene un atributo que es un booleano que indica 
si la direccion es la principal o no-->
<!ATTLIST address main (yes|no) #IMPLIED>
<!ELEMENT street (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== cassiuste/MO373-DTDs/Ejercicio1/contact.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE contact SYSTEM "contact.dtd">

<contact familyMember="no">
    <name>John</name>
    <lastName>Smith</lastName>
    <mobileNum>6551245</mobileNum>
    <landlineNum>45879542</landlineNum>
    <age>42</age>
    <address main="yes">
        <street></street>
        <postalCode></postalCode>
        <city></city>
    </address>
    <email>johnsmith@gmail.com</email>
</contact>
<contact familyMember="yes">
    <name>Maria</name>
    <lastName>Martinez</lastName>
    <mobileNum>611254875</mobileNum>
    <landlineNum>47090140</landlineNum>
    <age>25</age>
    <address main="no">Talcahuano 1323</address>
    <email>mmariamartinez12@hotmail.com</email>
</contact>

=== cassiuste/MO373-DTDs/contact/contact.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE contacts SYSTEM "contact.dtd">
<contacts>
    <contact familyMember="no">
        <name>John</name>
        <lastName>Smith</lastName>
        <mobileNum>6551245</mobileNum>
        <landlineNum>45879542</landlineNum>
        <age>42</age>
        <address main="yes">
            <street>Franklin 522</street>
            <postalCode>1603</postalCode>
            <city>Buenos Aires</city>
        </address>
        <email>johnsmith@gmail.com</email>
    </contact>
    <contact familyMember="yes">
        <name>Maria</name>
        <lastName>Martinez</lastName>
        <mobileNum>611254875</mobileNum>
        <landlineNum>47090140</landlineNum>
        <age>25</age>
        <address main="yes">
            <street>Diagonal 1607</street>
            <postalCode>08002</postalCode>
            <city>Barcelona</city>
        </address>
        <email>mmariamartinez12@hotmail.com</email>
    </contact>
</contacts>
